management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  application:
    name: traceTest

opentracing:
  jaeger:
    http-sender:
      url: http://158.179.167.191:14268/api/traces # tempo host

server:
  port: 8080
#  port: 8088 API ?? ???? ??


